"""Test agent module for AutoData multi-agent system.

This module provides the Test agent that debugs, executes, and tests code
generated by other agents.
"""

import asyncio
import logging
from typing import Any

from easydict import EasyDict  # type: ignore
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from typing_extensions import override

from autodata.agents.base_agent import BaseAgent
from autodata.core.exceptions import AutoDataModelError
from autodata.core.ohcache.formatter import TestAgentResponse
from autodata.prompts import TEST_AGENT_INSTRUCTION
from autodata.tools.python_tool import execute_python_snippet, resolve_work_dir

logger = logging.getLogger("AutoData.agents")


class TestAgent(BaseAgent):
    """Test agent that debugs, executes, and tests code generated by other agents.

    This agent is responsible for ensuring code quality, functionality, and
    reliability through comprehensive testing and debugging.
    """

    description: str = "tests for code quality and functionality"
    agent_name: str = "TestAgent"
    instruction: str = Field(default=TEST_AGENT_INSTRUCTION)
    formatter: type[BaseModel] | PydanticOutputParser = Field(default=TestAgentResponse)

    def _execute_code(self, code: str) -> dict[str, Any]:
        """Execute code using the Python REPL tool.

        Args:
            code: Python code to execute.

        Returns:
            Dictionary containing execution results and metrics.
        """
        try:
            work_dir = resolve_work_dir(self.config)
            if not code.strip():
                return {
                    "execution_result": "No executable code provided.",
                }

            result = execute_python_snippet(code, work_dir=work_dir)
            return {"execution_result": result}

        except Exception as e:
            logger.error(f"Error executing code: {str(e)}")
            return {"execution_result": f"Error during execution: {str(e)}"}

    def _extract_code_snippet(self, messages: list[Any]) -> str:
        """Extract the latest code snippet from the conversation history."""

        if not messages:
            return ""

        latest_message = messages[-1]
        content = getattr(latest_message, "content", "")
        return content if isinstance(content, str) else ""

    def _analyze_code_quality(self, code: str, execution_result: str) -> dict[str, Any]:
        """Analyze code quality and provide recommendations.

        Args:
            code: The Python code to analyze.
            execution_result: Result from code execution.

        Returns:
            Dictionary containing quality metrics and recommendations.
        """
        recommendations = []
        quality_score = 0.5  # Base score

        # Check for basic code quality indicators
        if "def " in code or "class " in code:
            quality_score += 0.1

        if '"""' in code or "'''" in code:
            quality_score += 0.1
            recommendations.append("Good: Code includes docstrings")
        else:
            recommendations.append(
                "Consider adding docstrings for better documentation"
            )

        if "try:" in code and "except" in code:
            quality_score += 0.1
            recommendations.append("Good: Code includes error handling")
        else:
            recommendations.append(
                "Consider adding error handling with try-except blocks"
            )

        if "import " in code:
            quality_score += 0.1

        # Check execution result for errors
        if "Error" in execution_result or "Exception" in execution_result:
            quality_score -= 0.2
            recommendations.append("Code execution failed - review and fix errors")

        # Ensure score is between 0 and 1
        quality_score = max(0.0, min(1.0, quality_score))

        return {"code_quality_score": quality_score, "recommendations": recommendations}

    @override
    def forward_step(self, context: EasyDict) -> EasyDict:  # type: ignore[override]
        """Test and debug code based on the current state."""

        current_model = context.get("model")
        if current_model is None:
            raise AutoDataModelError("TestAgent requires an initialized language model")

        contextual_state = context.get("state") or EasyDict()
        state_messages = contextual_state.get("messages", [])
        if not isinstance(state_messages, list):
            state_messages = [state_messages]
        contextual_state["messages"] = state_messages

        code_to_test = self._extract_code_snippet(state_messages)
        execution_info = self._execute_code(code_to_test)
        execution_result = execution_info.get("execution_result", "")

        quality_info = self._analyze_code_quality(code_to_test, execution_result)

        chain = context.get("chain")
        if chain is None:
            chain = self._get_chain(current_model)
        try:
            response: TestAgentResponse = self._invoke_chain_with_retry(
                chain, contextual_state
            )
        except Exception:  # noqa: BLE001
            logger.exception("Error in test agent forward")
            raise

        response.execution_result = execution_result

        metrics = dict(response.performance_metrics or {})
        if "code_quality_score" in quality_info:
            metrics["code_quality_score"] = quality_info["code_quality_score"]
        response.performance_metrics = metrics

        if quality_info.get("recommendations"):
            response.recommendations = list(quality_info["recommendations"])

        logger.info("Test agent completed testing")
        context.result = response
        return context

    async def forward_step_async(
        self, context: EasyDict
    ) -> EasyDict:  # type: ignore[override]
        """Async parity wrapper to execute the synchronous pipeline."""

        return await asyncio.to_thread(self.forward_step, context)
