"""Validation agent module for AutoData multi-agent system.

This module provides the Validation agent that executes and validates code
generated by the EngineerAgent, installing dependencies and debugging errors.
"""

from __future__ import annotations

import ast
import asyncio
import json
import logging
import re
from pathlib import Path
from typing import Any

from easydict import EasyDict
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.runnables import RunnableLambda
from pydantic import BaseModel, Field
from typing_extensions import override

from autodata.agents.base_agent import BaseAgent
from autodata.agents.types import AgentState
from autodata.core.exceptions import AgentStateError
from autodata.core.ohcache.formatter import ValidationAgentResponse
from autodata.prompts import VALIDATION_AGENT_INSTRUCTION
from autodata.tools.python_tool import (
    execute_with_dependencies,
    resolve_work_dir,
)

logger = logging.getLogger("AutoData.agents")


class ValidationAgent(BaseAgent):
    """Validation agent that executes and validates code from EngineerAgent.

    This agent is responsible for:
    - Installing Python dependencies in Docker containers
    - Executing generated code in isolated environments
    - Debugging and fixing errors automatically
    - Validating code output and correctness
    - Providing detailed execution reports

    The agent uses Docker containers to ensure reproducible, isolated execution
    with automatic dependency management.
    """

    # ============================================================================
    # Class Fields
    # ============================================================================

    description: str = "executes and validates code with dependency management"
    agent_name: str = "ValidationAgent"
    instruction: str = Field(default=VALIDATION_AGENT_INSTRUCTION)
    formatter: type[BaseModel] | PydanticOutputParser = Field(
        default=ValidationAgentResponse
    )
    enable_think_stage: bool = False

    # ============================================================================
    # Public Methods - Overrides
    # ============================================================================

    def forward_step(self, context: EasyDict) -> EasyDict:  # type: ignore[override]
        """Execute and validate code produced by the EngineerAgent."""

        chain = context.get("chain") or self.chain
        state = context.get("state")
        if chain is None or state is None:
            raise AgentStateError("ValidationAgent requires prepared state and chain")

        response = self._invoke_chain_with_retry(chain, state)
        logger.info("Validation completed with status: %s", response.validation_status)
        context.result = response
        return context

    async def forward_step_async(
        self, context: EasyDict
    ) -> EasyDict:  # type: ignore[override]
        """Async wrapper that mirrors the synchronous validation flow."""

        return await asyncio.to_thread(self.forward_step, context)

    @override
    def __call__(self, state: AgentState) -> EasyDict:
        """Synchronous entrypoint maintained for BaseAgent compatibility."""

        return self.forward(state)

    @override
    async def __acall__(self, state: AgentState) -> EasyDict:
        """Async entrypoint delegating to `aforward` for parity."""

        return await self.aforward(state)

    # ============================================================================
    # BaseAgent overrides
    # ============================================================================

    def _build_chain(self) -> None:
        """Build chain that performs validation without an LLM."""
        self.chain = RunnableLambda(self._run_validation_flow)

    # ============================================================================
    # Private Methods - Core Workflow
    # ============================================================================

    def _run_validation_flow(self, state: AgentState) -> ValidationAgentResponse:
        """Execute code validation and build a structured response."""
        validation_settings = self._get_validation_settings()
        max_attempts = validation_settings.max_execution_attempts
        docker_image = validation_settings.docker_image
        timeout = validation_settings.timeout_seconds

        code, dependencies = self._extract_code_from_state(state)

        if not code:
            return self._create_no_code_response()

        logger.info("Validating code with %s declared dependencies", len(dependencies))

        work_dir = resolve_work_dir(self.config)
        execution_result: dict[str, Any] | None = None
        attempt_count = 0

        for attempt in range(1, max_attempts + 1):
            attempt_count = attempt
            logger.info("Validation attempt %s/%s", attempt, max_attempts)

            result = execute_with_dependencies(
                code=code,
                dependencies=dependencies,
                work_dir=work_dir,
                image=docker_image,
                timeout=timeout,
            )

            execution_result = result.to_legacy_payload()
            execution_result["metadata"] = result.metadata

            if execution_result.get("success"):
                logger.info("Code execution succeeded on attempt %s", attempt)
                break

            logger.warning(
                "Code execution failed on attempt %s/%s", attempt, max_attempts
            )

            if attempt == max_attempts:
                break

        feedback = self._build_feedback(execution_result, dependencies)
        return self._build_validation_response(
            execution_result=execution_result,
            attempt_count=attempt_count,
            dependencies=dependencies,
            feedback=feedback,
        )

    # ============================================================================
    # Private Methods - Code Extraction
    # ============================================================================

    def _extract_code_from_state(self, state: AgentState) -> tuple[str, list[str]]:
        """Extract Python code and dependencies from state messages.

        Looks for EngineerAgent responses in the message history and extracts
        the code and dependencies fields.

        Args:
            state: Current agent state with message history

        Returns:
            Tuple of (code: str, dependencies: list[str])
        """
        messages = state.get("messages", [])
        if not messages:
            return "", []

        engineer_message = None
        for message in reversed(messages):
            if getattr(message, "name", "") == "EngineerAgent":
                engineer_message = message
                break

        if engineer_message is None:
            logger.warning("No EngineerAgent message available in state")
            return "", []

        content = getattr(engineer_message, "content", "")
        if not content:
            logger.warning("EngineerAgent message contained no content")
            return "", []

        parsed = self._try_parse_message_content(content)

        dependencies: list[str] = []
        if parsed:
            dependencies = list(parsed.get("dependencies", []) or [])
            if "code" in parsed and parsed.get("code"):
                logger.info("Extracted code from EngineerAgent response payload")
                return parsed.get("code", ""), dependencies

        message_text = ""
        if isinstance(parsed, dict):
            message_text = parsed.get("message", "")
        if not message_text:
            message_text = content

        script_path = self._parse_script_path(message_text)
        if script_path:
            path_obj = Path(script_path)
            if path_obj.is_file():
                try:
                    code_text = path_obj.read_text()
                    logger.info("Loaded engineer script from %s", path_obj)
                    return code_text, dependencies
                except OSError as exc:
                    logger.error(
                        "Failed to read engineer script %s: %s",
                        path_obj,
                        exc,
                    )
            else:
                logger.warning(
                    "Engineer script path %s does not exist", path_obj
                )

        cache_key = self._parse_cache_key(message_text)
        if cache_key:
            cached = self.fetch_artifact(cache_key, default=None)
            if isinstance(cached, dict):
                cached_code = cached.get("code")
                cached_deps = cached.get("dependencies") or []
                if cached_code:
                    logger.info("Fetched code from cache artifact %s", cache_key)
                    if not dependencies:
                        dependencies = list(cached_deps)
                    return cached_code, dependencies

        logger.warning("Unable to locate engineer code payload for validation")
        return "", dependencies

    def _try_parse_message_content(self, content: str) -> dict[str, Any] | None:
        """Try to parse message content as dictionary or JSON.

        Args:
            content: Message content string

        Returns:
            Parsed dictionary or None if parsing fails
        """
        # Try parsing as JSON
        try:
            return json.loads(content)
        except (json.JSONDecodeError, TypeError):
            pass

        try:
            return ast.literal_eval(content)
        except (ValueError, SyntaxError):
            pass

        match = re.search(r"\{.*\}", content, re.DOTALL)
        if match:
            dict_str = match.group(0)
            for parser in (json.loads, ast.literal_eval):
                try:
                    return parser(dict_str)
                except Exception:  # noqa: BLE001 - fall back to regex parsing
                    continue

        # Try extracting code and dependencies with regex
        code_match = re.search(r"['\"]code['\"]:\s*['\"](.+?)['\"]", content, re.DOTALL)
        deps_match = re.search(
            r"['\"]dependencies['\"]:\s*\[(.*?)\]", content, re.DOTALL
        )

        if code_match:
            code = code_match.group(1)
            deps = []
            if deps_match:
                deps_str = deps_match.group(1)
                deps = [
                    d.strip().strip("'\"") for d in deps_str.split(",") if d.strip()
                ]
            return {"code": code, "dependencies": deps}

        return None

    def _parse_script_path(self, text: str) -> str | None:
        match = re.search(r"Script saved to ([^\s)]+)", text)
        if not match:
            return None
        return match.group(1).rstrip(".")

    def _parse_cache_key(self, text: str) -> str | None:
        match = re.search(r"Cached artifact key: ([^\s.]+)", text)
        if not match:
            return None
        return match.group(1).strip()

    # ============================================================================
    # Private Methods - Response Building
    # ============================================================================

    def _build_validation_response(
        self,
        execution_result: dict[str, Any] | None,
        attempt_count: int,
        dependencies: list[str],
        feedback: list[str],
    ) -> ValidationAgentResponse:
        """Build a ValidationAgentResponse from execution results.

        Args:
            execution_result: Result from execute_with_dependencies
            attempt_count: Number of attempts made
            dependencies: List of dependencies
            feedback: Actionable feedback for the EngineerAgent

        Returns:
            ValidationAgentResponse with all fields populated
        """
        safe_result = execution_result or {}
        success = safe_result.get("success", False)
        execution_output = safe_result.get("execution_output", "")
        install_log = safe_result.get("install_log", "")
        error_message = safe_result.get("error_message")

        error_text = (error_message or "").lower()
        if success:
            execution_status = "SUCCESS"
        elif "timeout" in error_text:
            execution_status = "TIMEOUT"
        elif execution_output or error_message:
            execution_status = "ERROR"
        else:
            execution_status = "NOT_EXECUTED"

        # Extract errors from output
        execution_errors = self._extract_errors(execution_output, error_message)

        if success and not feedback:
            validation_status = "PASS"
        elif success and feedback:
            validation_status = "PARTIAL"
        else:
            validation_status = "FAIL"

        recommendations = self._generate_recommendations(
            safe_result, feedback, validation_status
        )

        return ValidationAgentResponse(
            validation_status=validation_status,
            execution_status=execution_status,
            execution_output=execution_output,
            execution_errors=execution_errors,
            environment_setup_log=install_log,
            dependencies_installed=dependencies if success else [],
            feedback=feedback,
            attempt_count=attempt_count,
            recommendations=recommendations,
            error_message=error_message,
        )

    def _extract_errors(
        self, execution_output: str, error_message: str | None
    ) -> list[str]:
        """Extract specific error messages from execution output.

        Args:
            execution_output: Full execution output
            error_message: Error message if any

        Returns:
            List of extracted error strings
        """
        errors = []

        # Add main error message
        if error_message:
            errors.append(error_message)

        # Extract Python exceptions from output
        error_patterns = [
            r"(.*?Error: .*)",
            r"(.*?Exception: .*)",
            r"(Traceback \(most recent call last\):.*?)(?=\n\n|\Z)",
        ]

        for pattern in error_patterns:
            matches = re.findall(pattern, execution_output, re.DOTALL)
            errors.extend(matches)

        return errors[:10]  # Limit to 10 most relevant errors

    def _build_feedback(
        self, execution_result: dict[str, Any] | None, dependencies: list[str]
    ) -> list[str]:
        """Construct actionable feedback for the EngineerAgent."""
        if not execution_result:
            return [
                "Validation did not run. Provide code and dependency details for execution."
            ]

        if execution_result.get("success"):
            return []

        feedback: list[str] = []
        error_message = execution_result.get("error_message")
        execution_output = execution_result.get("execution_output", "")

        if error_message:
            feedback.append(f"Execution error: {error_message}")

        extracted = self._extract_errors(execution_output, error_message)
        for error in extracted:
            trimmed = error.strip()
            if trimmed and trimmed not in feedback:
                feedback.append(trimmed)

        if not dependencies and any(
            marker in execution_output
            for marker in ["ModuleNotFoundError", "ImportError"]
        ):
            feedback.append(
                "No dependencies were installed. Ensure required pip packages are listed under 'dependencies'."
            )

        if not feedback:
            feedback.append(
                "Review execution logs for detailed errors and update the script accordingly."
            )

        return feedback[:5]

    def _generate_recommendations(
        self,
        execution_result: dict[str, Any],
        feedback: list[str],
        validation_status: str,
    ) -> list[str]:
        """Generate recommendations based on validation results.

        Args:
            execution_result: Execution result dictionary
            feedback: Actionable feedback items
            validation_status: Overall validation status

        Returns:
            List of recommendation strings
        """
        recommendations = []

        if validation_status == "PASS":
            recommendations.append("Code executed successfully without errors.")

        elif validation_status == "PARTIAL":
            recommendations.append(
                "Code executed successfully, but review the feedback items to harden the solution."
            )

        elif validation_status == "FAIL":
            error_msg = execution_result.get("error_message", "")
            if "timeout" in error_msg.lower():
                recommendations.append(
                    "Execution timed out; collaborate with EngineerAgent to optimise the script or adjust the timeout."
                )
            elif "docker" in error_msg.lower():
                recommendations.append(
                    "Docker is unavailable; ensure Docker is installed, running, and accessible."
                )
            else:
                recommendations.append(
                    "Code execution failed. EngineerAgent should address the reported issues and resubmit."
                )
            if feedback:
                recommendations.append(
                    "Ensure each feedback item is resolved before the next validation run."
                )

        return recommendations

    def _create_no_code_response(self) -> ValidationAgentResponse:
        """Create response when no code is found in state."""
        return ValidationAgentResponse(
            validation_status="FAIL",
            execution_status="NOT_EXECUTED",
            execution_output="",
            execution_errors=["No code found in previous messages"],
            environment_setup_log="",
            dependencies_installed=[],
            feedback=[
                "No EngineerAgent code response detected. Provide a code payload with 'code' and 'dependencies' fields."
            ],
            attempt_count=0,
            recommendations=[
                "Ensure EngineerAgent has generated code before validation"
            ],
            error_message="No code found to validate",
        )

    # ============================================================================
    # Private Methods - Configuration
    # ============================================================================

    def _get_validation_settings(self) -> EasyDict:
        """Return validation configuration with sane defaults."""
        raw_config = getattr(self.config, "validation_config", {}) or {}
        settings = EasyDict(raw_config)

        try:
            settings.max_execution_attempts = max(
                1, int(settings.get("max_execution_attempts", 3))
            )
        except (TypeError, ValueError):
            settings.max_execution_attempts = 3

        settings.docker_image = settings.get(
            "docker_image", "jupyter/scipy-notebook:latest"
        )

        try:
            settings.timeout_seconds = max(1, int(settings.get("timeout_seconds", 300)))
        except (TypeError, ValueError):
            settings.timeout_seconds = 300

        return settings
